require: rubocop-rails

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
Metrics/MethodLength:
  Max: 50
Metrics/AbcSize:
  IgnoredMethods: ['respond_to']

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
