version: "3.7"
services:
  db:
    restart: unless-stopped
  web:
    restart: unless-stopped
  sidekiq:
    restart: unless-stopped
  redis:
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
