version: "3.7"
services:
  db:
    image: mariadb
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - gems:/usr/local/bundle
    ports:
      - "${PORT}:3000"
    environment:
      - PORT=${PORT}
      - RAILS_ENV
      - RAILS_LOG_TO_STDOUT
      - RAILS_SERVE_STATIC_FILES
    depends_on:
      - db

volumes:
  mysql:
  gems:
