version: "3.7"

x-app: &app
  build: .
  volumes:
    - .:/myapp
    - gems:/usr/local/bundle
  environment:
    PORT:
    RAILS_ENV:
    RAILS_LOG_TO_STDOUT:
    RAILS_SERVE_STATIC_FILES:
    MARIADB_ROOT_PASSWORD:
    EDITOR: vi
    REDIS_PASSWORD:
  image: portal_web
  stdin_open: true
  tty: true

services:

  db:
    image: mariadb
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD

  web:
    <<: *app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "${PORT}:3000"
    depends_on:
      - db
      - redis

  sidekiq:
    <<: *app
    command: bundle exec sidekiq -q default -q mailers
    environment:
      - RAILS_ENV
      - MARIADB_ROOT_PASSWORD
      - REDIS_URL_SIDEKIQ
      - REDIS_PASSWORD
    depends_on:
      - redis
      - db

  runner:
    <<: *app
    command: /bin/bash
    ports:
      - '4000:4000'
    depends_on:
      - db
      - selenium_chrome

  selenium_chrome:
    image: selenium/standalone-chrome-debug:3.141.59-selenium
    volumes:
      - ./tmp/capybara/downloads:/home/seluser/Downloads
    shm_size: 2G
    ulimits:
      memlock: -1
      nofile:
        soft: 4096
        hard: 8192
    logging:
      driver: none
    ports:
      - "5900:5900"
      - "4444:4444"

  redis:
    image: bitnami/redis:latest
    volumes:
      - redis:/bitnami/redis
    environment:
      REDIS_PASSWORD:

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"  # Web interface
      - "1025:1025"  # SMTP server
    restart: unless-stopped

volumes:
  mysql:
  redis:
  gems:
