version: "3.7"

x-app: &app
  build: .
  volumes:
    - .:/myapp
    - gems:/usr/local/bundle
  environment:
    - PORT
    - RAILS_ENV
    - RAILS_LOG_TO_STDOUT
    - RAILS_SERVE_STATIC_FILES
    - MARIADB_ROOT_PASSWORD
  image: portal_web

services:

  db:
    image: mariadb
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD

  web:
    <<: *app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "${PORT}:3000"
    depends_on:
      - db

  runner:
    <<: *app
    tty: true
    command: /bin/bash
    ports:
      - '4000:4000'
    depends_on:
      - db

volumes:
  mysql:
  gems:
