# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb9c34c9f3b245436d5d64d0500832ebbf03272f057a755a00e44b263ea757989acacdada366033874539ad3ae19330454a38b4907886c117d22a5ab38a43b5d

test:
  secret_key_base: 4954d534b3b83a7fcabd6b681acd1f338f536720d3954248b504da32b08fa6e71b3a4bfa8de0070a03dc902fbdfa622fe3e68e7cf0c97098b728df70e269b9af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
